Vagrant.require_version ">= 1.8.0"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "app_python"

  config.vm.provider "virtualbox" do |v|
    v.name = "app_python"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/playbooks/docker/main.yml"
    ansible.config_file = "../../ansible/ansible.cfg"
    ansible.extra_vars = {
      username: "vagrant"
    }
  end

end