apiVersion: v1
kind: Secret
metadata:
  name: { { include "app-python.fullname" . } }
  labels: { { include "app-python.labels" . | nindent 4 } }
type: Opaque
data:
  secret_string: { { .Value.secret_string | b64enc | quote } }
