Vagrant.require_version ">= 1.8.0"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "docker-vm"
  config.vm.network "forwarded_port", guest: 8000, host: 1234

  config.vm.provider "virtualbox" do |v|
    v.name = "docker-vm"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../ansible/playbooks/docker/main.yml"
    ansible.config_file = "../../ansible/ansible.cfg"
    ansible.extra_vars = {
      username: "vagrant"
    }
  end

end