name: Python App Continuous Integration
on:
  push:
    branches:  [ main ] 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
      
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner"
      - run: echo "The workflow is now ready to test your code on the runner"
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}" 
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r app_python/requirements.txt
     
      - name: Test with unittest
        run: |
          cd app_python
          python3 -m unittest test_main.py
